# Generated by Django 4.1 on 2022-08-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
